# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Clock for mobile and open platforms ⏰ 🕓 🕰"
REPO_LICENSE=""
REPO_TOPICS="clock,godot-application,ios-app,macos-app"

# URLs section
REPO_GIT_SSH="git@github.com:fini-net/fini-clock.git"
REPO_WEB_URL="https://github.com/fini-net/fini-clock"

# Derived values
REPO_ORG_NAME="fini-net"
REPO_REPO_NAME="fini-clock"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "clock"
    "godot-application"
    "ios-app"
    "macos-app"
)
